# Generated by Django 3.1.7 on 2021-03-30 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em')),
                ('status', models.BooleanField(default=True)),
                ('lista_nome', models.CharField(max_length=50, verbose_name='Nome da Lista')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em')),
                ('status', models.BooleanField(default=True)),
                ('item_nome', models.CharField(max_length=50, verbose_name='Nome Item')),
                ('item_quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em')),
                ('status', models.BooleanField(default=True)),
                ('relative_name', models.CharField(max_length=50, verbose_name='Nome Completo')),
                ('relative_birth', models.DateField(max_length=10, verbose_name='Data de Nascimento')),
                ('relative_grade', models.CharField(max_length=10, verbose_name='Ciclo/Série')),
                ('relative_school', models.CharField(max_length=50, verbose_name='Escola')),
                ('relative_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.listamaterial', verbose_name='Responsavel')),
                ('relative_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsavel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='listamaterial',
            name='lista_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.material', verbose_name='Items'),
        ),
    ]
