# Generated by Django 3.1.7 on 2021-03-30 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relative',
            name='relative_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.listamaterial', verbose_name='Lista de Materiais'),
        ),
    ]
