# Generated by Django 3.1.7 on 2021-03-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210330_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listamaterial',
            name='lista_item',
        ),
        migrations.AddField(
            model_name='listamaterial',
            name='lista_item',
            field=models.ManyToManyField(to='core.Material', verbose_name='Items'),
        ),
    ]
