# Generated by Django 3.1.7 on 2021-03-30 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210330_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listamaterial',
            name='lista_item',
        ),
        migrations.AddField(
            model_name='material',
            name='lista_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.listamaterial', verbose_name='Lista de Materiais'),
        ),
    ]
