# Generated by Django 3.1.7 on 2021-04-01 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20210330_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listamaterial',
            options={'verbose_name': 'Lista de Material', 'verbose_name_plural': 'Lista de Materiais'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materiais'},
        ),
        migrations.AlterModelOptions(
            name='relative',
            options={'verbose_name': 'Dependente', 'verbose_name_plural': 'Dependentes'},
        ),
        migrations.CreateModel(
            name='PontosColeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em')),
                ('status', models.BooleanField(default=True)),
                ('ponto_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('ponto_endereco', models.CharField(max_length=80, verbose_name='Endereço')),
                ('ponto_numero', models.PositiveIntegerField(verbose_name='Numero')),
                ('ponto_bairro', models.CharField(max_length=30, verbose_name='Bairro')),
                ('ponto_tipo', models.CharField(max_length=20, verbose_name='Tipo')),
                ('ponto_uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2, verbose_name='Estado')),
                ('relative_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsavel')),
            ],
            options={
                'verbose_name': 'Ponto de Coleta',
                'verbose_name_plural': 'Pontos de Coleta',
            },
        ),
    ]
