# Generated by Django 3.1.7 on 2021-04-02 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('materiais', '0004_auto_20210402_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='listamaterial',
            name='dependente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.dependente', verbose_name='Nome'),
        ),
    ]
