# Generated by Django 3.1.7 on 2021-04-02 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('materiais', '0005_listamaterial_dependente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listamaterial',
            name='dependente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.dependente', verbose_name='Dependente'),
        ),
        migrations.AlterField(
            model_name='listamaterial',
            name='nome',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nome'),
        ),
    ]
