# Generated by Django 3.1.7 on 2021-04-02 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PontosColeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Atualizado em')),
                ('status', models.BooleanField(default=True)),
                ('ponto_nome', models.CharField(max_length=50, verbose_name='Nome do Local')),
                ('ponto_cnpj', models.CharField(max_length=50, verbose_name='CNPJ')),
                ('ponto_cep', models.CharField(max_length=80, verbose_name='CEP')),
                ('ponto_cidade', models.CharField(max_length=80, verbose_name='Cidade')),
                ('ponto_uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='SP', max_length=2, verbose_name='Estado')),
                ('ponto_bairro', models.CharField(max_length=30, verbose_name='Bairro')),
                ('ponto_endereco', models.CharField(max_length=80, verbose_name='Endereço')),
                ('ponto_numero', models.PositiveIntegerField(verbose_name='Numero')),
                ('ponto_telefone', models.CharField(max_length=20, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Ponto de Coleta',
                'verbose_name_plural': 'Pontos de Coleta',
            },
        ),
    ]
